services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - db_data:/var/lib/mysql
      - ./web-app/server/db/subsync.sql:/docker-entrypoint-initdb.d/subsync.sql
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "${DB_USER}", "-p${DB_PASS}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  backend:
    build:
      context: ./web-app/server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      DB_HOST: "db"
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
      CLIENT_PORT: 5173
      NODE_PORT: 3000
      HOME_IP: "localhost"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "pgrep node || exit 1"] # Check if a node process is running
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped

  frontend:
    build:
      context: ./web-app/subsync
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://localhost:3000
    ports:
      - "80:80"
    environment:
      NGINX_HOST: 0.0.0.0
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped

volumes:
  db_data:
